baseURL = 'https://jaemin-baek.github.io/'
languageCode = 'en-us'
theme = "stack"
title = 'ë°±ì¬ë¯¼ ê¸°ìˆ ë¸”ë¡œê·¸'


[params]
  mainSections = ["post"]
  featuredImageField = "image"
  rssFullContent = true
  favicon = "" 

  [params.footer]
    since = 2020
    customText = ""

  [params.colorScheme]
    toggle = true
    default = "light" 

  [params.sidebar]
    emoji = "ğŸ“š"
    subtitle = "@WEMADE"
    [params.sidebar.avatar]
      enabled = true
      local = true
      src = "img/avatar.png"

  [params.imageProcessing.cover]
    enabled = true

  [params.imageProcessing.content]
    enabled = true

  [params.widgets]
    # í™ˆí˜ì´ì§€ ìœ„ì ¯ ì„¤ì •
    homepage = [
      { type = "search" },
      { type = "archives" },
      { type = "categories" },
      { type = "tag-cloud" },
      # ë‹¤ë¥¸ ìœ„ì ¯ë“¤...
    ]

[menu]
  [[menu.main]]

  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/jaemin-baek"
    [menu.social.params]
      icon = "brand-github"
